name: backend
description: A Dart-native backend for scraping and aggregating news.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  http: ^1.1.0
  xml: ^6.3.0
  html: ^0.15.4
  crypto: ^3.0.3
  intl: ^0.19.0
  core:
    path: ../core

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
